# -*- coding: utf-8 -*-
"""Python_For

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13PbWUbx75596UfsLhq9qb5psqo1YhvQ7

1. Faça um programa que leia 5 números e informe o maior número.
"""

#EX1

#Leia 5 numeros
#Informe o maior numero
#Variaveis declaradas dentro de blocos de codigo nao sao localizadas fora dele, apenas quando declaradas fora "sem identacao"

maior_numero = float("-inf") #Ou maior_numero =  0

for contador in range (5): #Os blocos de codigo sao identificados pela identacao
  numero = float(input(f"digite o {contador+1} numero: ")) #A varivel e o numero que sera imputado, nao o contador
  if numero > maior_numero:
    maior_numero = numero
  print(f"o maior numero digitado e: {maior_numero}")

"""2. Faça um programa que verifique e mostre os números entre 1.000 e 2.000
(inclusive) que, quando divididos por 11 produzam resto igual a 2.
"""

#EX2
for numeros in range(1000, 2001): #O intervalo numero ja foi definido, nao e necessario imputar numeros
  if numeros %11 == 2: #numeros do intervalo que sao divisiveis "%" e o resto igual a 2
    print(numeros)

"""3. Faça um programa que leia 5 números e informe a soma e a média dos
números.
"""

#EX3
soma = 0

for numero_rep in range (5):
  numero = float(input(f"digite o {numero_rep+1} numero: "))
  soma += numero

print(soma/(numero_rep+1))

"""4. Faça um programa que receba um número e usando laços de repetição
calcule e mostre a tabuada desse número.
"""

#EX4
numero = int(input("Digite um número para descobrir a sua tabuada: "))
print(f"Tabuada de {numero}:")

for contador in range (1,11):
  resultado = numero*contador
  print(f"{numero} x {contador} = {resultado}")

"""5. Faça um programa que mostre as tabuadas dos números de 1 a 10 usando
laços de repetição.
"""

#EX5

for num in range(1,11): #Laco de 1 a 10
  for i in range(1,11): #Laco para a multiplicacao de 1 a 10

"""6. Faça um programa que imprima na tela os números de 1 a 20, um abaixo
do outro. Depois modifique o programa para que ele mostre os números
um ao lado do outro.
"""

#EX6

for numero in range(1, 21):
   print(numero)

print(list(range(1, 21)))

"""7. Faça um programa que imprima na tela apenas os números ímpares entre
1 e 50.
"""

#EX7

for numb in range (1, 51):
  if numb %2 != 0: #If numb %2 == 0 retorna numeros pares
   print(numb)

"""8. Faça um programa que receba dois números inteiros e gere os números
inteiros que estão no intervalo compreendido por eles.
"""

#EX8
for numb_int in range(2):
  numb_int = int(input(f"Insira o {numb_int+1}º número: "))
for i in range(numb_int+1, numb_int+1):

#Adicionando dois inputs distintos e mais facil de determinar o range entre os dois numeros

"""9. Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi
superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor
mostre na tela uma mensagem contendo em quanto foi superado o
faturamento.
"""

#EX9

for cliente in range(5):
  cliente = int(input(f"Digite o valor de compra do {cliente+1}º cliente: "))

lojaB = 54000

if cliente > lojaB:
  print(f"A meta foi superada em {cliente - lojaB}")
else:
  print(f"O faturamento foi de {cliente}")

"""10. Faça um programa que peça 10 números inteiros, calcule e mostre a
quantidade de números pares e a quantidade de números impares.
"""

#EX10

numeros_pares = 0
numeros_inteiros = 0

for i in range (1,11):
  numero = int(input(f"Digite o numero inteiro {numero}: "))